/* Lista ejecutiva de proyectos: separa saldo de caja de resultado económico. */
(function(){'use strict';
  var G=window.GRANJA, MO=window.MANOOBRA, proys=G.proyectos();
  var ICONO={BIOINSUMOS:'🧪',HUERTA:'🥬',CAFE_CENICAFE_I:'☕',GANADO_BOVINO:'🐄',CODORNICES:'🥚',GALLINAS_PONEDORAS:'🐔',CONEJOS:'🐰',POLLOS:'🐤',APICOLA:'🐝',CERDOS:'🐷',OVINOS:'🐑',PISCICOLA:'🐟',PINO_ROMERON:'🌲',AMBIENTE_CREATIVO:'🌳',PINO_PATULA:'🌲',OTRO_MADERAS:'🪵',OTROS_GRANJA:'🏡'};
  function cop(v){return G.cop(Math.round(v));} function signo(v){return v>0?'+'+cop(v):cop(v);} function cls(v){return v>0?'text-success-700':v<0?'text-danger-700':'text-neutral-500';}
  function render(){
    var por=G.porProyecto(G.movimientosDelPeriodo()), mapa={};por.forEach(function(x){mapa[x.proyecto]=x;});
    var fArea=(document.getElementById('f-area')||{}).value||'',fResp=(document.getElementById('f-resp')||{}).value||'',fEstado=(document.getElementById('f-estado')||{}).value||'';
    var datos=proys.map(function(p){var c=mapa[p.codigo]||{ingresos:0,egresos:0,balance:0};var m=MO.repartoProyecto(p.codigo,'B_OPERACION',7);var sin=!c.ingresos&&!c.egresos&&!m.costoTotal;return {p:p,c:c,m:m,resultado:(c.balance||0)-(m.costoTotal||0),sin:sin};});
    var lista=datos.filter(function(x){return(!fArea||x.p.area===fArea)&&(!fResp||x.p.responsable===fResp)&&(!fEstado||(fEstado==='Con pérdida'?x.resultado<0:fEstado==='Positivo'?x.resultado>0:x.sin));});
    lista.sort(function(a,b){return a.resultado-b.resultado;});
    var neg=datos.filter(function(x){return x.resultado<0;}).length,pos=datos.filter(function(x){return x.resultado>0;}).length,sin=datos.filter(function(x){return x.sin;}).length;
    var filas=lista.map(function(x){if(x.sin)return '<tr><td>'+(ICONO[x.p.codigo]||'📌')+' <a href="proyecto?p='+x.p.codigo+'">'+G.esc(x.p.nombre)+'</a></td><td>'+G.esc(x.p.responsable)+'</td><td colspan="4" class="text-neutral-500">Sin actividad registrada; no evaluable</td></tr>';return '<tr><td>'+(ICONO[x.p.codigo]||'📌')+' <a href="proyecto?p='+x.p.codigo+'">'+G.esc(x.p.nombre)+'</a></td><td>'+G.esc(x.p.responsable)+'</td><td class="money">'+cop(x.c.ingresos)+'</td><td class="money '+cls(x.c.balance)+'">'+signo(x.c.balance)+'</td><td class="money text-purple-700">≈ '+cop(x.m.costoTotal)+'</td><td class="money '+cls(x.resultado)+'"><strong>'+signo(x.resultado)+'</strong></td></tr>';}).join('');
    document.getElementById('seccion-lista').innerHTML='<div class="alerta-roja"><strong>Lectura ejecutiva:</strong> '+neg+' proyectos presentan resultado económico negativo, '+pos+' positivo y '+sin+' no tienen actividad suficiente para evaluarse. El saldo de caja no incluye el personal.</div><div class="cuadro-cuerpo mt-4"><form class="flex flex-wrap gap-3 mb-4 text-sm" aria-label="Filtros"><label>Área <select id="f-area"><option value="">Todas</option>'+Array.from(new Set(proys.map(function(p){return p.area;}))).map(function(a){return '<option '+(a===fArea?'selected':'')+'>'+G.esc(a)+'</option>';}).join('')+'</select></label><label>Responsable <select id="f-resp"><option value="">Todos</option>'+Array.from(new Set(proys.map(function(p){return p.responsable;}))).map(function(a){return '<option '+(a===fResp?'selected':'')+'>'+G.esc(a)+'</option>';}).join('')+'</select></label><label>Resultado <select id="f-estado"><option value="">Todos</option><option '+(fEstado==='Con pérdida'?'selected':'')+'>Con pérdida</option><option '+(fEstado==='Positivo'?'selected':'')+'>Positivo</option><option '+(fEstado==='Sin actividad'?'selected':'')+'>Sin actividad</option></select></label></form><div class="overflow-x-auto"><table><thead><tr><th>Proyecto</th><th>Responsable</th><th class="text-right">Ingresos</th><th class="text-right">Saldo caja</th><th class="text-right">MO atribuida</th><th class="text-right">Resultado económico</th></tr></thead><tbody>'+filas+'</tbody></table></div><p class="text-xs text-neutral-500 mt-3">≈ La atribución de mano de obra por proyecto es una estimación. La pérdida global de la granja no depende de este reparto.</p></div>';
    ['f-area','f-resp','f-estado'].forEach(function(id){document.getElementById(id).addEventListener('change',render);});
  } render(); if(window.ESTADO&&ESTADO.alCambiar)ESTADO.alCambiar(render);
})();
