window.INFORME_SEGUIMIENTO = (function () {
  'use strict';
  const S=window.SEGUIMIENTO, U=window.SEGUIMIENTO_UI, G=window.GRANJA;
  const esc=G.esc, val=U.value, num=U.number, table=U.table;
  const labels={Id:'Identificador',SourceId:'Fuente',SourceLocation:'Ubicación',ProjectId:'Proyecto',Date:'Fecha',OriginalDate:'Fecha original',DatePrecision:'Precisión de fecha',Kind:'Tipo de registro',Species:'Especie',Scope:'Grupo / alcance',Count:'Número',Quantity:'Cantidad',Unit:'Unidad',Notes:'Observaciones',Sex:'Sexo',Stage:'Etapa',CoverageComplete:'Cobertura completa acreditada',ReviewStatus:'Revisión',Quality:'Calidad',Product:'Producto',Warehouse:'Bodega',Kg:'Kilos',Group:'Grupo',SupplyMode:'Origen del suministro',Amount:'Valor',Direction:'Ingreso / egreso',Price:'Precio',Detail:'Detalle',Damaged:'Dañados',GrossIncludesDamage:'Producción incluye dañados',Allocations:'Distribución',Treatment:'Tratamiento',Dose:'Dosis',Composition:'Composición',Name:'Nombre'};
  function selected(rows, code) { const id=S.projectId(code); return (rows || []).filter(r=>!code || r.ProjectId===id); }
  function title(id) { const p=(S.data().Projects || []).find(p=>p.Id===id); return p?p.Name:'Sin proyecto identificado'; }
  function render(code='', at='2026-07-31') {
    const d=S.data(), e=window.DATA_EVIDENCIAS || {}, projects=selectedProjects(code), reviews=selected(d.Reviews,code);
    let html='<h1>Informe para el director de pasantía</h1><p>Inventario de activos, producción contextualizada y seguimiento documental de la Granja San José. No reemplaza un inventario físico ni una validación institucional.</p>'+
      '<nav class="seguimiento-enlaces" aria-label="Apartados del informe"><a href="#matriz">Inventario y áreas</a><a href="#produccion">Producción</a><a href="#alimentacion">Alimentación</a><a href="#actividades">Actividades</a><a href="#personal">Personal</a><a href="#revisiones">Por revisar</a><a href="#fuentes">Fuentes</a></nav>'+
      '<div class="seguimiento-filtros no-imprimir"><label for="filtro-proyecto">Proyecto</label><select id="filtro-proyecto"><option value="">Todos los proyectos</option>'+(d.Projects || []).map(p=>'<option value="'+esc(p.Code)+'"'+(p.Code===code?' selected':'')+'>'+esc(p.Name)+'</option>').join('')+'</select><label for="fecha-censo">Censos hasta</label><input id="fecha-censo" type="date" value="'+esc(at)+'"><button type="button" class="btn-sec" id="imprimir-seguimiento">Imprimir informe</button></div>'+
      '<section class="seguimiento-panel" id="matriz"><h2>Inventario y áreas por proyecto</h2><p>Una fila por proyecto, incluso cuando no hay información. Los números corresponden a últimos censos por grupo hasta '+esc(G.fecha(at))+'. Las fechas, cobertura y fuentes se consultan en cada ficha.</p>'+
      table(['Proyecto','Número / último censo por grupo','Hembras / machos','Etapa','Especie / variedad','Género taxonómico','Hectáreas / alcance','Pendientes'],projects.map(p=>{
        const censuses=S.census(p.Id,at), assets=(d.Assets || []).filter(a=>a.ProjectId===p.Id), land=assets.filter(a=>a.AreaHa!=null), species=[...new Set(censuses.map(a=>a.Species).concat(assets.map(a=>a.Species || a.Variety),p.ReportedScientificNames || [],p.ReportedVarieties || []).filter(Boolean))], crops=assets.filter(a=>a.Kind==='crop_census' && a.Quantity!=null);
        return ['<a href="seguimiento?p='+encodeURIComponent(p.Code)+'">'+esc(p.Name)+'</a>',censuses.length?censuses.map(r=>val(r.Scope)+': '+num(r.Count)+' ('+val(r.Date)+')').join('<br>'):crops.length?crops.map(r=>num(r.Quantity)+' '+val(r.Unit)+' · '+val(r.Name)+' (fecha pendiente)').join('<br>'):val(null),censuses.some(r=>U.sex(r))?censuses.map(r=>val(r.Scope)+': '+val(U.sex(r))).join('<br>'):val(null),val(censuses.map(r=>r.Stage).filter(Boolean).join('; ')),species.length?esc(species.join('; ')):val(null),val(censuses.map(r=>r.Genus).filter(Boolean).concat(p.ReportedGenera || []).join('; ')),land.length?land.map(a=>num(a.AreaHa)+' ha · '+val(a.Name)+(a.SharedArea?' (conjunto, no sumar por lote)':'')).join('<br>'):val(null),String((d.Reviews || []).filter(r=>r.ProjectId===p.Id).length)+' revisiones · <a href="proyecto?p='+encodeURIComponent(p.Code)+'">Ficha →</a>'];
      }),'Requerimientos del director: cantidad, sexo, etapa productiva, área y especie / variedad')+
      '<p class="seguimiento-nota">Las áreas de 315 m² (0,0315 ha) de huerta, 1,34 ha del conjunto de café y 4 ha del conjunto de Pino Romerón son reportadas por S05, sin fecha de medición. No se publican como superficie total verificada de la granja. No se infieren hembras a partir del nombre de la especie.</p></section>';
    if(code && projects[0]) html+=U.inventory(code,at);
    html+='<section class="seguimiento-panel" id="produccion"><h2>Producción y porcentaje de postura</h2><p>El volumen de huevos por sí solo no mide rendimiento. Solo se calcula postura con población productiva fechada, completa y confirmada para el mismo alcance de recolección.</p>';
    for(const p of projects.filter(p=>p.Id==='P05' || p.Id==='P06')) {
      const rows=selected(e.Production,p.Code).filter(r=>r.Unit==='huevos' && r.Kind==='production').map(r=>({fecha:r.Date,unidades:r.Quantity}));
      html+='<h3>'+esc(p.Name)+'</h3>'+U.posture(p.Code,rows);
    }
    html+=evidenceDetails('Production','Registros de producción y cosecha',code,e)+'</section>';
    const feed=selected(e.Feed,code), totalKg=feed.reduce((s,r)=>s+(r.Kg || 0),0), feedGroups={};
    for(const r of feed){const key=(r.ProjectId || '')+'|'+(r.Group || ''); const g=feedGroups[key] || (feedGroups[key]={project:r.ProjectId,group:r.Group,kg:0,dates:new Set()});g.kg+=r.Kg || 0;if(r.Date)g.dates.add(r.Date);}
    html+='<section class="seguimiento-panel" id="alimentacion"><h2>Alimentación y existencias en bodega</h2><p>'+feed.length+' registros · '+num(totalKg)+' kg reportados. Fuente S03: 1 de mayo–3 de agosto de 2026. Los kilos se registran por grupo; no se interpretan como consumo por animal sin confirmación. Cero registros significa ausencia de registros, no ausencia de consumo.</p>'+
      table(['Proyecto','Grupo','Kilos reportados','Días con registro'],Object.values(feedGroups).map(g=>[esc(title(g.project)),val(g.group),num(g.kg),String(g.dates.size)]),'Consumo reportado por proyecto / grupo')+
      '<p class="dato-pendiente"><strong>Existencia en bodega: no calculable.</strong> Faltan inventario inicial o conteo aceptado, identificación del alimento, bodega de origen y entradas/salidas conciliadas. Compras menos consumo no demuestra por sí solo el saldo real.</p><details><summary>¿Qué hacer?</summary><p>Realizar conteo de apertura por alimento y bodega, registrar recepciones, transferencias y ajustes con soporte; vincular cada consumo a la salida correspondiente sin descontarlo dos veces. Saldo teórico = apertura + entradas − salidas; comparar con conteo físico.</p></details>'+evidenceDetails('Feed','Detalle de alimentación',code,e)+evidenceDetails('Supplies','Compras y fichas de suministros',code,e)+'</section>';
    const activities=selected(d.Activities,code);
    html+='<section class="seguimiento-panel" id="actividades"><h2>Actividades y seguimiento de agosto</h2><p>Los registros sin proyecto identificable permanecen sin asignación; no se reparten arbitrariamente. Cantidades planeadas vacías no se reemplazan por cero y no se agregan tareas de unidades diferentes.</p>'+
      table(['Proyecto','Actividad','Periodo / semana reportados','Planeado','Ejecutado','Acompañamiento','Observaciones','Fuente'],activities.map(r=>[esc(title(r.ProjectId)),val(r.Activity),val(r.OriginalDate),num(r.Planned),num(r.Executed),val(r.Accompanying),val(r.Notes),U.source(r)]),'Cumplimiento documentado de actividades')+'</section>';
    html+='<section class="seguimiento-panel" id="personal"><h2>Personal, funciones y dedicación</h2><p>Estos nueve cargos fueron solicitados por el director. Identidad vigente, funciones desglosadas por proyecto y porcentajes de dedicación no se aportaron en esta fuente. Los escenarios económicos de <a href="mano-obra">Mano de obra</a> siguen siendo estimaciones, no horas medidas.</p>'+
      table(['Cargo','Vinculación','Nombre vigente','Funciones por proyecto','Dedicación %','Horas','Fuente'],(d.Personnel || []).map(r=>[val(r.Position),val(r.EmploymentType),val(r.Person),val(r.Functions),num(r.Percent),num(r.Hours),U.source(r)]),'Datos de personal requeridos; no se inventan nombres ni dedicaciones')+
      '<details><summary>¿Qué hacer?</summary><p>Solicitar a coordinación la relación vigente de personas y funciones por cargo, y registrar dedicación por periodo y proyecto. Validar que la asignación de cada persona no exceda el 100 % del mismo periodo, separando operación, sanidad, administración y proyectos.</p></details></section>';
    html+='<section class="seguimiento-panel" id="revisiones"><h2>Propuestas pendientes de revisión humana</h2><p>'+reviews.length+' asuntos en este filtro. El color amarillo identifica pendientes, no correcciones confirmadas. Las propuestas no sustituyen la caja vigente del sitio ni el original.</p>'+
      table(['Proyecto','Fuente / ubicación','Campo','Original','Propuesta aproximada','Motivo','Decisión'],reviews.map(r=>[esc(title(r.ProjectId)),U.source(r),val(r.Field),val(r.OriginalJson),val(r.ProposedJson),val(r.Reason),'<span class="dato-pendiente">'+esc(r.Decision || 'pending')+'</span>']),'Auditoría: conservar original, propuesta y explicación')+
      evidenceDetails('CashOriginal','Caja del libro original',code,e)+evidenceDetails('CashTranscription','Caja de la transcripción',code,e)+evidenceDetails('Cash','Vista de trabajo con propuestas (no validada)',code,e)+evidenceDetails('Animals','Eventos y referencias de animales',code,d)+evidenceDetails('Assets','Activos y unidades territoriales',code,d)+evidenceDetails('Health','Registros sanitarios',code,e)+'</section>';
    html+='<section class="seguimiento-panel" id="fuentes"><h2>Fuentes y cortes independientes</h2>'+table(['ID','Fuente','Desde','Corte / fecha reportada'],(d.Sources || []).map(r=>[val(r.Id),val(r.Name),val(r.From),val(r.Cut)]),'No mezclar cortes de distintas fuentes')+
      '<p class="dato-pendiente">Hay investigaciones, áreas operativas y actividades mencionadas que no coinciden de forma inequívoca con los 17 proyectos del catálogo (por ejemplo carbono del suelo, graminario y bancos forrajeros). Se conservan en su fuente y sin asignación forzada; requieren confirmar catálogo y responsables.</p>'+
      (e.NarrativeSources || []).map(r=>'<details><summary>Leer transcripción documental completa '+esc(r.Id)+' (incluye referencias no normalizadas)</summary><p>'+esc(r.Text)+'</p></details>').join('')+
      '<p>Funciones de pasantía: validar planillas y base de datos; seguimiento de costos, gastos e ingresos; colaboración en reportes financieros; mejores prácticas administrativas; estrategias para objetivos de costos; demás actividades contables y financieras.</p><p>Este informe no publica documentos de identidad, teléfonos o correo del estudiante ni adjuntos privados. Las fechas originales ambiguas y los textos sin estructura conservan su ubicación documental.</p></section>';
    return html;
  }
  function selectedProjects(code){return (S.data().Projects || []).filter(p=>!code || p.Code===code);}
  function evidenceDetails(key,name,code,data){return '<details data-evidence="'+key+'"><summary>'+esc(name)+' ('+selected(data[key],code).length+')</summary><div class="evidencia-cuerpo"></div></details>';}
  function evidence(key,code){const data=['Animals','Assets'].includes(key)?S.data():(window.DATA_EVIDENCIAS || {});return table(['Proyecto','Fuente / ubicación','Contenido documental'],selected(data[key],code).map(r=>[esc(title(r.ProjectId)),U.source(r),Object.entries(r).filter(([k])=>!['ProjectId','SourceId','SourceLocation','Id','RequestId'].includes(k)).map(([k,v])=>'<strong>'+esc(labels[k] || k)+':</strong> '+val(typeof v==='object' && v!==null?JSON.stringify(v):v)).join('<br>')]),'Datos de fuente; cantidades de referencia no se suman como movimientos');}
  if(typeof document !== 'undefined') {
    const root=document.getElementById('informe-seguimiento');
    if(root){let code=G.qs('p') || '', at=G.qs('corte') || '2026-07-31'; if(!/^\d{4}-\d{2}-\d{2}$/.test(at))at='2026-07-31';
      function show(){root.innerHTML=render(code,at);document.getElementById('filtro-proyecto').addEventListener('change',function(){code=this.value;update();});document.getElementById('fecha-censo').addEventListener('change',function(){if(this.value){at=this.value;update();}});document.getElementById('imprimir-seguimiento').addEventListener('click',()=>window.print());root.querySelectorAll('[data-evidence]').forEach(el=>el.addEventListener('toggle',()=>{if(el.open&&!el.dataset.loaded){el.querySelector('.evidencia-cuerpo').innerHTML=evidence(el.dataset.evidence,code);el.dataset.loaded='yes';}}));}
      function update(){const url=new URL(location.href);if(code)url.searchParams.set('p',code);else url.searchParams.delete('p');url.searchParams.set('corte',at);history.replaceState(null,'',url);show();} show();
    }
  }
  return {render,evidence};
})();
