(function(){
  'use strict';
  var G=window.GRANJA, MO=window.MANOOBRA, D=window.DATA_MANOOBRA, root=document.getElementById('tablero');
  if(!root||!G||!MO||!D)return;
  var meses=7, movimientos=G.movimientosDelPeriodo(), caja=G.totales(movimientos), personal=MO.totalGranjaMes()*meses;
  var costo=caja.egresos+personal, resultadoGlobal=caja.ingresos-costo, porCaja=G.porProyecto(movimientos), escenarioActual=D.escenarioPorDefecto||'B_OPERACION';
  function cop(v){return G.cop(Math.round(v||0));} function esc(v){return G.esc(v==null?'':String(v));}
  function pct(v,d){return(+v||0).toLocaleString('es-CO',{minimumFractionDigits:d==null?1:d,maximumFractionDigits:d==null?1:d})+' %';}
  function clase(v){return v>0?'positivo':(v<0?'negativo':'neutro');} function signo(v){return v>0?'+'+cop(v):cop(v);}
  function datosProyectos(id){return G.proyectos().map(function(p){var c=porCaja.filter(function(x){return x.proyecto===p.codigo;})[0]||{ingresos:0,egresos:0,balance:0};var mo=MO.repartoProyecto(p.codigo,id,meses);return{codigo:p.codigo,nombre:p.nombre,ingresos:c.ingresos||0,egresos:c.egresos||0,caja:c.balance||0,manoObra:mo.costoTotal||0,resultado:(c.balance||0)-(mo.costoTotal||0)};});}
  function resumenEscenario(id){var ps=datosProyectos(id),est=MO.estructuraPeriodo(id,meses);return{id:id,nombre:MO.escenario(id).nombre,atribucion:personal-est.total,estructura:est.total,negativos:ps.filter(function(p){return p.resultado<0;}).length,positivos:ps.filter(function(p){return p.resultado>0;}).length,ceros:ps.filter(function(p){return p.resultado===0;}).length,peor:ps.slice().sort(function(a,b){return a.resultado-b.resultado;})[0]};}
  function descripcion(id){var textos={A_SOLO_CAJA:'No distribuye personal. Sirve para aislar el movimiento de caja, pero no muestra el costo económico de cada proyecto.',B_OPERACION:'Distribuye operación y sanidad mediante inductores observables; conserva dirección y sede como estructura. Es la lectura recomendada.',C_OPERACION_SEDE:'Añade servicios generales de sede al reparto. Útil para analizar una carga operativa más amplia.',D_ABSORCION_PLENA:'Distribuye todo el personal, incluida dirección. Muestra absorción total, con mayor incertidumbre por proyecto.'};return textos[id]||'';}
  function botonEscenario(e){return'<button type="button" class="v5-escenario-opcion" data-escenario="'+esc(e.id)+'" aria-pressed="'+(e.id===escenarioActual?'true':'false')+'"><strong>'+esc(e.nombre.split('·')[0].trim())+'</strong><span>'+esc(e.nombre.split('·').slice(1).join('·').trim())+'</span></button>';}
  function render(){
    var ps=datosProyectos(escenarioActual), e=MO.escenario(escenarioActual), est=MO.estructuraPeriodo(escenarioActual,meses), atribuido=personal-est.total;
    var orden=ps.slice().sort(function(a,b){return a.resultado-b.resultado;}), maxAbs=orden.reduce(function(m,p){return Math.max(m,Math.abs(p.resultado));},1);
    var neg=ps.filter(function(p){return p.resultado<0;}).length,pos=ps.filter(function(p){return p.resultado>0;}).length,cero=ps.filter(function(p){return p.resultado===0;}).length;
    var barras=orden.map(function(p){var ancho=Math.max(2,Math.round(Math.abs(p.resultado)/maxAbs*100));return'<button type="button" class="v5-resultado-fila v5-proyecto-control" data-proyecto="'+esc(p.codigo)+'" aria-expanded="false" aria-controls="v5-dashboard-detalle"><span class="v5-resultado-nombre">'+esc(p.nombre)+'</span><span class="v5-resultado-pista"><i class="'+clase(p.resultado)+'" style="width:'+ancho+'%"></i></span><strong class="'+clase(p.resultado)+'">'+signo(p.resultado)+'</strong></button>';}).join('');
    var filas=orden.map(function(p){return'<tr><td><button type="button" class="v5-tabla-proyecto v5-proyecto-control" data-proyecto="'+esc(p.codigo)+'" aria-expanded="false" aria-controls="v5-dashboard-detalle">'+esc(p.nombre)+'</button></td><td class="money">'+cop(p.ingresos)+'</td><td class="money">'+cop(p.egresos)+'</td><td class="money '+clase(p.caja)+'">'+signo(p.caja)+'</td><td class="money estimado">≈ '+cop(p.manoObra)+'</td><td class="money '+clase(p.resultado)+'"><strong>'+signo(p.resultado)+'</strong></td></tr>';}).join('');
    var comparaciones=(D.escenarios||[]).map(function(x){var r=resumenEscenario(x.id);return'<tr class="'+(x.id===escenarioActual?'v5-seleccionado':'')+'"><td><button type="button" class="v5-link-escenario" data-escenario="'+esc(x.id)+'">'+esc(r.nombre)+'</button></td><td class="money">'+cop(r.atribucion)+'</td><td class="money">'+cop(r.estructura)+'</td><td class="money">'+r.negativos+'</td><td class="money">'+r.positivos+'</td><td>'+esc(r.peor.nombre)+'</td><td class="money negativo">'+signo(r.peor.resultado)+'</td></tr>';}).join('');
    var porMes=G.porMes(movimientos),maxMes=porMes.reduce(function(m,x){return Math.max(m,x.ingresos,x.egresos);},1);
    var mesesHtml=porMes.map(function(x){return'<div class="v5-mes"><strong>'+esc(G.mesLabel(x.mes))+'</strong><span><b>Entró</b><i><em class="ingreso" style="width:'+Math.max(2,Math.round(x.ingresos/maxMes*100))+'%"></em></i><small class="positivo">'+cop(x.ingresos)+'</small></span><span><b>Salió</b><i><em class="egreso" style="width:'+Math.max(2,Math.round(x.egresos/maxMes*100))+'%"></em></i><small class="negativo">'+cop(x.egresos)+'</small></span></div>';}).join('');
    var cat={};movimientos.forEach(function(m){if(m.egresos){var k=m.producto||'Sin categoría';cat[k]=(cat[k]||0)+m.egresos;}});var categorias=Object.keys(cat).map(function(k){return{nombre:k,valor:cat[k]};}).sort(function(a,b){return b.valor-a.valor;});var maxCat=categorias.length?categorias[0].valor:1;
    var catHtml=categorias.map(function(x){return'<div class="v5-componente"><span>'+esc(x.nombre)+'</span><i><em style="width:'+Math.max(2,Math.round(x.valor/maxCat*100))+'%"></em></i><strong>'+cop(x.valor)+'</strong><small>'+pct(caja.egresos?x.valor/caja.egresos*100:0,1)+'</small></div>';}).join('');
    var pools=MO.porPool(), nombres={P_OPERACION:'Operación de campo',P_SANIDAD:'Sanidad y planeación',P_DIRECCION:'Dirección y supervisión',P_SEDE:'Servicios generales'};
    var poolHtml=Object.keys(pools).map(function(k){return'<article><span>'+esc(nombres[k]||k)+'</span><strong class="v5-monto-pool">'+cop(pools[k]*meses)+'</strong><small>'+pct(personal?pools[k]*meses/personal*100:0,1)+' del personal</small></article>';}).join('');
    root.innerHTML='<section class="v5-dashboard-cab"><div><p class="v5-eyebrow">Análisis económico interactivo</p><h1>Dashboard de escenarios de atribución</h1><p>El escenario modifica <strong>dónde se presenta el costo del personal</strong>, no la pérdida total de la granja. Use esta herramienta para explorar decisiones, no para evaluar personas.</p></div><aside><span>Resultado global — igual en A, B, C y D</span><strong class="v5-monto-dashboard">'+signo(resultadoGlobal)+'</strong><small>La distribución interna no crea ni elimina costos.</small></aside></section>'+
    '<section class="v5-panel v5-selector" aria-labelledby="v5-selector"><div class="v5-panel-cab"><div><p class="v5-eyebrow">Control del análisis</p><h2 id="v5-selector">Seleccione un escenario</h2></div><span class="v5-recomendado">B es el recomendado</span></div><div class="v5-escenarios" role="group" aria-label="Escenarios de atribución">'+(D.escenarios||[]).map(botonEscenario).join('')+'</div><div class="v5-escenario-lectura"><div><span>Escenario activo</span><strong>'+esc(e.nombre)+'</strong><p>'+esc(descripcion(escenarioActual))+'</p></div><div><span>Personal atribuido a proyectos</span><strong class="v5-monto-resumen">'+cop(atribuido)+'</strong></div><div><span>Estructura no atribuida</span><strong class="v5-monto-resumen">'+cop(est.total)+'</strong></div></div></section>'+
    '<section class="v5-kpis v5-kpis-dashboard"><article><span>Ingresos</span><strong class="v5-monto-kpi">'+cop(caja.ingresos)+'</strong><small>Dato del libro</small></article><article><span>Egresos de caja</span><strong class="v5-monto-kpi">'+cop(caja.egresos)+'</strong><small>Dato del libro</small></article><article><span>Personal</span><strong class="v5-monto-kpi">'+cop(personal)+'</strong><small>Dato de Talento Humano</small></article><article><span>Cobertura</span><strong class="v5-monto-kpi">'+pct(costo?caja.ingresos/costo*100:0,2)+'</strong><small>Ingresos ÷ costo total</small></article></section>'+
    '<section class="v5-panel"><div class="v5-panel-cab"><div><p class="v5-eyebrow">Efecto del escenario seleccionado</p><h2>Resultado estimado por proyecto</h2></div><p>'+neg+' negativos · '+pos+' positivos · '+cero+' en cero</p></div><div class="v5-resultado-grafico">'+barras+'</div><section id="v5-dashboard-detalle" class="v5-detalle" hidden aria-live="polite"></section><p class="v5-nota"><strong>≈ Estimación:</strong> no existen horas por proyecto. En '+esc(e.nombre)+', se atribuyen '+cop(atribuido)+' y permanecen '+cop(est.total)+' como estructura.</p></section>'+
    '<section class="v5-panel"><div class="v5-panel-cab"><div><p class="v5-eyebrow">Comparación de sensibilidad</p><h2>Qué cambia entre A, B, C y D</h2></div><p>Seleccione el nombre de un escenario para aplicarlo</p></div><div class="overflow-x-auto"><table><thead><tr><th>Escenario</th><th class="text-right">MO atribuida</th><th class="text-right">Estructura</th><th class="text-right">Con pérdida</th><th class="text-right">Positivos</th><th>Mayor pérdida</th><th class="text-right">Resultado</th></tr></thead><tbody>'+comparaciones+'</tbody></table></div><p class="v5-nota">La suma de resultados de proyectos más la estructura siempre concilia con <strong>'+signo(resultadoGlobal)+'</strong>. Lo que cambia es la asignación analítica.</p></section>'+
    '<section class="v5-panel"><div class="v5-panel-cab"><div><p class="v5-eyebrow">Trazabilidad completa</p><h2>Detalle del escenario '+esc(e.nombre)+'</h2></div><button type="button" class="btn-sec no-imprimir" id="v5-imprimir-dashboard">Imprimir</button></div><div class="overflow-x-auto"><table><thead><tr><th>Proyecto</th><th class="text-right">Ingresos</th><th class="text-right">Egresos</th><th class="text-right">Saldo caja</th><th class="text-right">MO atribuida</th><th class="text-right">Resultado</th></tr></thead><tbody>'+filas+'</tbody><tfoot><tr><th colspan="4">Estructura no atribuida</th><th class="money">'+cop(est.total)+'</th><th class="money negativo">−'+cop(est.total)+'</th></tr><tr><th colspan="5">RESULTADO GLOBAL</th><th class="money negativo">'+signo(resultadoGlobal)+'</th></tr></tfoot></table></div></section>'+
    '<section class="v5-panel"><div class="v5-panel-cab"><div><p class="v5-eyebrow">Comportamiento de caja</p><h2>Entradas y salidas por mes</h2></div><p>La escala es común para comparar meses</p></div><div class="v5-meses">'+mesesHtml+'</div></section>'+
    '<section class="v5-dos-columnas"><article class="v5-panel"><p class="v5-eyebrow">Composición de egresos</p><h2>En qué salió el dinero</h2><div class="v5-componentes">'+catHtml+'</div></article><article class="v5-panel"><p class="v5-eyebrow">Costo institucional</p><h2>Cómo se compone el personal</h2><div class="v5-pools">'+poolHtml+'</div><p class="v5-nota">Nueve cargos, equivalentes a 7,70 dedicaciones completas. Los valores ya incluyen prestaciones.</p></article></section>'+
    '<section class="v5-panel v5-metodologia"><details><summary>Metodología, supuestos y límites</summary><div><p><strong>Dato:</strong> ingresos y egresos provienen del libro de caja; '+cop(MO.totalGranjaMes())+' mensuales provienen de Talento Humano.</p><p><strong>Supuesto temporal:</strong> se aplica de enero a julio la planta informada al corte de julio.</p><p><strong>Estimación:</strong> operación usa un ICO compuesto; sanidad usa carga animal y eventos. Sede y dirección solo se reparten en C o D.</p><p><strong>Límite:</strong> no se midieron horas ni se monetizó el valor académico, social o investigativo.</p></div></details></section>';
    conectar();
  }
  function conectar(){root.querySelectorAll('[data-escenario]').forEach(function(b){b.addEventListener('click',function(){escenarioActual=this.dataset.escenario;render();});});root.querySelectorAll('.v5-proyecto-control').forEach(function(b){b.addEventListener('click',function(){abrirDetalle(this.dataset.proyecto);});});var imp=document.getElementById('v5-imprimir-dashboard');if(imp)imp.addEventListener('click',function(){window.print();});}
  function abrirDetalle(codigo){var ps=datosProyectos(escenarioActual),p=ps.filter(function(x){return x.codigo===codigo;})[0];if(!p)return;var lista=movimientos.filter(function(m){return m.proyecto===codigo;}).sort(function(a,b){return String(b.fecha||'').localeCompare(String(a.fecha||''));});var panel=document.getElementById('v5-dashboard-detalle');root.querySelectorAll('.v5-proyecto-control').forEach(function(b){var a=b.dataset.proyecto===codigo;b.setAttribute('aria-expanded',a?'true':'false');b.classList.toggle('is-active',a);});panel.hidden=false;panel.dataset.cargado=codigo;var filas=lista.map(function(m){return'<tr><td class="whitespace-nowrap">'+esc(G.fecha(m.fecha)||m.fecha||'')+'</td><td>'+esc(m.detalle||m.producto||'')+'</td><td class="money positivo">'+(m.ingresos?cop(m.ingresos):'—')+'</td><td class="money negativo">'+(m.egresos?cop(m.egresos):'—')+'</td></tr>';}).join('');panel.innerHTML='<div class="v5-detalle-cab"><div><p class="v5-eyebrow">Detalle bajo '+esc(MO.escenario(escenarioActual).nombre)+'</p><h3>'+esc(p.nombre)+'</h3></div><button type="button" class="v5-cerrar" aria-label="Cerrar detalle">×</button></div><div class="v5-detalle-kpis"><article><span>Saldo caja</span><strong class="'+clase(p.caja)+'">'+signo(p.caja)+'</strong></article><article><span>MO atribuida</span><strong class="estimado">≈ '+cop(p.manoObra)+'</strong></article><article><span>Resultado estimado</span><strong class="'+clase(p.resultado)+'">'+signo(p.resultado)+'</strong></article><article><span>Registros de caja</span><strong>'+lista.length+'</strong></article></div>'+(lista.length?'<h4>Movimientos que sustentan la caja</h4><div class="v5-movimientos overflow-x-auto"><table><thead><tr><th>Fecha</th><th>Detalle</th><th class="text-right">Entró</th><th class="text-right">Salió</th></tr></thead><tbody>'+filas+'</tbody></table></div>':'<p class="v5-nota">No hay movimientos propios de caja en el periodo.</p>')+'<p class="v5-detalle-pie"><a href="proyecto?p='+encodeURIComponent(codigo)+'">Abrir ficha completa →</a></p>';panel.querySelector('.v5-cerrar').addEventListener('click',function(){panel.hidden=true;panel.innerHTML='';root.querySelectorAll('.v5-proyecto-control').forEach(function(b){b.setAttribute('aria-expanded','false');b.classList.remove('is-active');});});panel.scrollIntoView({behavior:'smooth',block:'nearest'});}
  render();
})();
